services:
  jdk11-nanoserver-1809:
    image: jdk11-nanoserver-1809
    build:
      context: ./windows/
      dockerfile: Dockerfile.nanoserver
      args:
        VERSION: ${DOCKER_AGENT_VERSION}
  jdk17-nanoserver-1809:
    image: jdk17-nanoserver-1809
    build:
      context: ./windows/
      dockerfile: Dockerfile.nanoserver
      args:
        VERSION: ${DOCKER_AGENT_VERSION}
  jdk11-windowsservercore-ltsc2019:
    image: jdk11-windowsservercore-ltsc2019
    build:
      context: ./windows/
      dockerfile: Dockerfile.windowsservercore
      args:
        VERSION: ${DOCKER_AGENT_VERSION}
  jdk17-windowsservercore-ltsc2019:
    image: jdk17-windowsservercore-ltsc2019
    build:
      context: ./windows/
      dockerfile: Dockerfile.windowsservercore
      args:
        VERSION: ${DOCKER_AGENT_VERSION}
